name: Firebase Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Firebase CLI
      - name: Install Firebase CLI
        run: sudo npm install -g firebase-tools
      
      # Step 4: Build the React app
      - name: Build React app
        run: sudo npm run build
        
      # Step 3: Deploy to Firebase
      - name: Firebase Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Store Firebase token in GitHub secrets
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
